<?php
/**
 * WorkbookWithLastRoomDate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vimbox\RoomsApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vimbox-rooms
 *
 * Beta
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vimbox\RoomsApi\Model;

use \ArrayAccess;

/**
 * WorkbookWithLastRoomDate Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Vimbox\RoomsApi
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WorkbookWithLastRoomDate implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'WorkbookWithLastRoomDate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id' => 'int',
        'lesson_id' => 'int',
        'lesson_rev_id' => 'int',
        'homework' => '\Vimbox\RoomsApi\Model\WorkbookHomeworkInfo',
        'test' => '\Vimbox\RoomsApi\Model\WorkbookTestInfo'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id' => 'id',
        'lesson_id' => 'lessonId',
        'lesson_rev_id' => 'lessonRevId',
        'homework' => 'homework',
        'test' => 'test'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id' => 'setId',
        'lesson_id' => 'setLessonId',
        'lesson_rev_id' => 'setLessonRevId',
        'homework' => 'setHomework',
        'test' => 'setTest'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id' => 'getId',
        'lesson_id' => 'getLessonId',
        'lesson_rev_id' => 'getLessonRevId',
        'homework' => 'getHomework',
        'test' => 'getTest'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['lesson_id'] = isset($data['lesson_id']) ? $data['lesson_id'] : null;
        $this->container['lesson_rev_id'] = isset($data['lesson_rev_id']) ? $data['lesson_rev_id'] : null;
        $this->container['homework'] = isset($data['homework']) ? $data['homework'] : null;
        $this->container['test'] = isset($data['test']) ? $data['test'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets lesson_id
     * @return int
     */
    public function getLessonId()
    {
        return $this->container['lesson_id'];
    }

    /**
     * Sets lesson_id
     * @param int $lesson_id
     * @return $this
     */
    public function setLessonId($lesson_id)
    {
        $this->container['lesson_id'] = $lesson_id;

        return $this;
    }

    /**
     * Gets lesson_rev_id
     * @return int
     */
    public function getLessonRevId()
    {
        return $this->container['lesson_rev_id'];
    }

    /**
     * Sets lesson_rev_id
     * @param int $lesson_rev_id
     * @return $this
     */
    public function setLessonRevId($lesson_rev_id)
    {
        $this->container['lesson_rev_id'] = $lesson_rev_id;

        return $this;
    }

    /**
     * Gets homework
     * @return \Vimbox\RoomsApi\Model\WorkbookHomeworkInfo
     */
    public function getHomework()
    {
        return $this->container['homework'];
    }

    /**
     * Sets homework
     * @param \Vimbox\RoomsApi\Model\WorkbookHomeworkInfo $homework
     * @return $this
     */
    public function setHomework($homework)
    {
        $this->container['homework'] = $homework;

        return $this;
    }

    /**
     * Gets test
     * @return \Vimbox\RoomsApi\Model\WorkbookTestInfo
     */
    public function getTest()
    {
        return $this->container['test'];
    }

    /**
     * Sets test
     * @param \Vimbox\RoomsApi\Model\WorkbookTestInfo $test
     * @return $this
     */
    public function setTest($test)
    {
        $this->container['test'] = $test;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Vimbox\RoomsApi\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Vimbox\RoomsApi\ObjectSerializer::sanitizeForSerialization($this));
    }
}


